### PR TITLE
Fixed #6

### LINKED ISSUE #6: NullPointerException at .MethodBody.toString() and it is obvious
The library throws null pointer exception when I call methodbody.toString().

`java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String at.pollaknet.api.facile.renderer.LanguageRenderer.renderAsReference(at.pollaknet.api.facile.symtab.symbols.Field)' on a null object reference
        at at.pollaknet.api.facile.metamodel.entries.FieldEntry.renderAsReference(FieldEntry.java:188)
        at at.pollaknet.api.facile.code.instruction.object.Stsfld.render(Stsfld.java:16)
        at at.pollaknet.api.facile.code.MethodBody.toString(MethodBody.java:695)`

### PR DESCRIPTION
**Pull request by yhs0602**
I made a workaround for the issue #6. `MethodBody.toString()` now creates a temporary `LanguageRenderer` with `null` `FacileReflector`.

### CODE REVIEW

**Comment by KYHSGeekCode** [comment]
@TomSmartBishop

**Comment by TomSmartBishop** [comment]
Thanks for your work @KYHSGeekCode !!!
It would be great however, if we don't need to pull the ILAsmRenderer into the toString method. The toString method should be independent of that.

I think we could just use this line to the toString method:
String.format("\nIL_%04x: %s", programCounter, i.toString());

(maybe also check if there is any CilInstuction that does something different than toString in it's render method)

**Comment by KYHSGeekCode** [comment]
> It would be great however, if we don't need to pull the ILAsmRenderer into the toString method. The toString method should be independent of that.

Perfectly agree with that.

**Comment by TomSmartBishop** [comment]
Just out of curious: Are you using the toString method instead of the ILAsmRender to get a string representation of the method body?

**Comment by KYHSGeekCode** [comment]
> Just curious: Are you using the toString method instead of the ILAsmRender to get a string representation of the method body?

I think I used to.
[(1)](https://github.com/KYHSGeekCode/Android-Disassembler/blob/d1ab40462bcc4aacb4218b885f85d5880ffa329f/app/src/main/java/com/kyhsgeekcode/disassembler/FileDrawerListItem.java#L37)

[(2)](https://github.com/KYHSGeekCode/Android-Disassembler/blob/62fe16cea41cd4ad9f0a224199c5645568aa7d17/app/src/main/java/com/kyhsgeekcode/disassembler/FileDrawerListItem.java#L37)

**Comment by TomSmartBishop** [comment]
Could you keep an IlAsmRenderer instance and just do a `String str = instance.render(methodBody, null);` instead?

**Comment by KYHSGeekCode** [comment]
> Could you keep an IlAsmRenderer instance and just do a `String str = instance.render(methodBody, null);` instead?

Oh I didn't know that that method existed. [However, isn't that method private?](https://github.com/TomSmartBishop/facile-api/blob/5b74a307b769f1ef44b3ce43b26dc74aa4f1741f/Facile/src/main/java/at/pollaknet/api/facile/renderer/ILAsmRenderer.java#L921)

File: Facile/src/main/java/at/pollaknet/api/facile/code/MethodBody.java [hunk 1]
```diff
@@ -1,786 +1,1180 @@
...
-				buffer.append(";");
-				index++;
-			}
-		}
-		buffer.append("\n\n\tCIL: ");
-		
-		int programCounter=0;
-	
-		for(CilInstruction i: getCilInstructions()) {
-			buffer.append(String.format("\nIL_%04x: %s", programCounter, i.render(null)));
```
Comment (KYHSGeekCode) [inline Facile/src/main/java/at/pollaknet/api/facile/code/MethodBody.java]: Logic changes here

File: Facile/src/main/java/at/pollaknet/api/facile/renderer/ILAsmRenderer.java [hunk 2]
```diff
@@ -932,13 +932,17 @@ private String render(MethodBody methodBody, DebugInformation debugInformation)
...
 		buffer.append(" byte");
 		
-		if(	methodBody.getMethodToken() == reflector.getCliHeader().getEntryPointToken() &&
-			!ByteReader.testFlags(	reflector.getCliHeader().getFlags(),
-									CliHeader.FLAGS_NATIVE_ENTRY_POINT		)				) {
-			buffer.append(newLine);
-			buffer.append(".entrypoint ");
+
+		if(reflector != null){
+			if(	methodBody.getMethodToken() == reflector.getCliHeader().getEntryPointToken() &&
```
Comment (KYHSGeekCode) [inline Facile/src/main/java/at/pollaknet/api/facile/renderer/ILAsmRenderer.java]: And here

File: Facile/src/main/java/at/pollaknet/api/facile/code/MethodBody.java [hunk 3]
```diff
@@ -1,786 +1,1180 @@
 package at.pollaknet.api.facile.code;
```
Comment (KYHSGeekCode) [inline Facile/src/main/java/at/pollaknet/api/facile/code/MethodBody.java]: All changes are just formatting and organizing imports. The only changes in logic are commented below

**Review by yhs0602 — COMMENTED** [review]
It uses CilInstruction.toString now

File: Facile/src/main/java/at/pollaknet/api/facile/code/MethodBody.java (hunk 3 above)
Comment (KYHSGeekCode) [reply Facile/src/main/java/at/pollaknet/api/facile/code/MethodBody.java]: Sorry for massive white space changes!

File: Facile/src/main/java/at/pollaknet/api/facile/renderer/ILAsmRenderer.java (hunk 2 above)
Comment (TomSmartBishop) [reply Facile/src/main/java/at/pollaknet/api/facile/renderer/ILAsmRenderer.java]: Maybe we can add a parameter to this method for the entry point token and make the method public

File: Facile/src/main/java/at/pollaknet/api/facile/code/MethodBody.java (hunk 3 above)
Comment (TomSmartBishop) [reply Facile/src/main/java/at/pollaknet/api/facile/code/MethodBody.java]: would you mind to revert and just copy&paste the re-organized imports and/or share your white-space settings with me to avoid such things in the future?

**Comment by TomSmartBishop** [comment]
> It uses CilInstruction.toString now

Ok, great I saw ther migt be some minor differences - eg. when resolving token names, so maybe the best thing is to make the render method in ILAamRenderer for the methodBOdy public so that you can use it in your app

**Comment by TomSmartBishop** [comment]
OK, PR looks good, now, but let's revert the white-space change. Again I'm happy to apply some white-space rules if we can agree on some standard (but in a separate commit)

**Comment by KYHSGeekCode** [comment]
Okay, I'll do when I'm back home.

**Review by yhs0602 — COMMENTED** [review]
Reverted whitespaces!

File: Facile/src/main/java/at/pollaknet/api/facile/code/MethodBody.java (hunk 3 above)
Comment (KYHSGeekCode) [reply Facile/src/main/java/at/pollaknet/api/facile/code/MethodBody.java]: > would you mind to revert and just copy&paste the re-organized imports and/or share your white-space settings with me to avoid such things in the future?

My white-space settings were intellij's default settings.

**Comment by KYHSGeekCode** [comment]
Just curious, did you(r team) write such a[ large and long switch-cases](https://github.com/TomSmartBishop/facile-api/blob/c8627397382e583c99eb823204bd226f6c123202/Facile/src/main/java/at/pollaknet/api/facile/code/MethodBody.java#L326) manually to develop a decompiler? Or are there any strategies for writing disassemblers like this project?

**Review by TomSmartBishop — APPROVED** [review]

**Comment by TomSmartBishop** [comment]
Good question indeed…I just applied theory from building compilers.
